
DROP TABLE IF EXISTS bilhete;
DROP TABLE IF EXISTS auditoria;
DROP TABLE IF EXISTS carteira;
DROP TABLE IF EXISTS carteira_empresa;
DROP TABLE IF EXISTS alerta;
DROP TABLE IF EXISTS rota;
DROP TABLE IF EXISTS utilizador;
DROP TABLE IF EXISTS perfil;

DROP DATABASE IF EXISTS felixbus;
